package lexico;

public enum TipoToken {
	OPMAIOR, OPMENOR, OPIGUAL,OPMENORIGUAL,
	OPMAIORIGUAL, OPDIFERENTE, OPAND, OPOR,
        OPARITMAIS, OPARITMENOS, OPARITMULTIPLICACAO,
        OPARITDIVISAO,
        DECLARACAOVARINI, NOMEVAR, FINALIZAVAR, 
        IDVAR, EOF, ERRO, PROGRAMAINICIO, 
        PROGRAMAFIM, OUTRAVAR, DECLARACAOVARFIM, 
        DECLARACAOSEINI, DECLARACAOSEFIM, FECHAMENTODETAG,
        DECLARACAOSENAOINI, DECLARACAOSENAOFIM,
        DECLARAENTAOINI, DECLARAENTAOFIM;
	
	
}
